Assignment 2

#1. Create a NumPy array containing integers from 0 to 9.

In [2]:
import numpy as np

In [3]:
arr1 = np.arange(1,10)
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

#2. Create a NumPy array from a given Python list [10, 20, 30, 40, 50]

In [4]:
arr1 = np.array([10,20,30,40,50])
arr1

array([10, 20, 30, 40, 50])

#3
. Create a 2D array (3x3) with values ranging from 0 to 8.

In [5]:
arr1 = np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#4. Given a 2D array, find its shape and size. Create a 5x4 array with random integers between 1 and 100, and print the shape and size.

In [6]:
arr1 = np.random.randint(1,100,20).reshape(5,4)
arr1

array([[86, 49, 36, 98],
       [95,  3, 97, 73],
       [ 8, 29, 49,  6],
       [91, 53, 66, 54],
       [ 9, 22, 61, 83]], dtype=int32)

In [7]:
arr1.shape

(5, 4)

In [8]:
arr1.size

20

#5. Create a 3x3 array of integers and access: a. The second element of the first row.

In [9]:
arr1 = np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [10]:
arr1[0,1]

np.int64(1)

#b. The third column of the 2nd row.

In [11]:
arr1[1,2]

np.int64(5)

#c. A subarray with the first two rows and last two columns.

In [12]:
arr1[:2,1:]

array([[1, 2],
       [4, 5]])

#6. Create a 1D array of 12 elements. Reshape it into a 3x4 2D array.

In [13]:
arr1 = np.arange(1,13)
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [14]:
arr1.reshape(3,4)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

#7. Reshape a 3x3 matrix into a 1D array.

In [15]:
arr1 = np.arange(0,9).reshape(3,3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [16]:
arr1.reshape(-1)

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

#8. Create two arrays of shape (2, 3): arr1 and arr2. Perform element-wise addition, subtraction, multiplication, and division on them.

In [31]:
op1 = np.array([[1,2,3],
               [4,5,6]])
                     
op1

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
op2 = np.array([[3,4,5],
                [6,7,8]])
op2

array([[3, 4, 5],
       [6, 7, 8]])

In [33]:
add = op1 + op2
add

array([[ 4,  6,  8],
       [10, 12, 14]])

In [34]:
sub = op2 - op1
sub

array([[2, 2, 2],
       [2, 2, 2]])

In [35]:
mul = op1 * op2
mul

array([[ 3,  8, 15],
       [24, 35, 48]])

In [36]:
div = op1 / op2
div

array([[0.33333333, 0.5       , 0.6       ],
       [0.66666667, 0.71428571, 0.75      ]])

#9. Use NumPy's built-in functions to compute the sum, mean, and standard deviation of a given array.

In [38]:
arr1 = np.random.randint(1,25,8)
arr1

array([16, 24, 20, 11,  1,  8, 13,  2], dtype=int32)

In [44]:
arr1.sum() # Return the sum of the array elements.

np.int64(95)

In [45]:
arr1.mean() #Returns the average of the array elements.

np.float64(11.875)

In [46]:
arr1.std() ## Returns the standard deviation of the array elements along given axis.

np.float64(7.606535019310698)

#10. Create a 2x2 matrix A and a 2x2 matrix B. Perform matrix multiplication using np.dot() or the @ operator.

In [57]:
m1 = np.array([[1,2],
              [3,4]])
m1

array([[1, 2],
       [3, 4]])

In [59]:
m2 = np.array([[5,6],
               [7,4]])
m2

array([[5, 6],
       [7, 4]])

In [66]:
m1 @ m2 ## Matrix multiplication

array([[19, 14],
       [43, 34]])

##11. Find the transpose of matrix A and matrix B.

In [72]:
m1 = np.array([[1,2],
              [3,4]])
m1

array([[1, 2],
       [3, 4]])

In [68]:
m1.T ## Transpose of matrix

array([[1, 3],
       [2, 4]])

In [73]:
m2 = np.array([[5,6],
               [7,4]])
m2

array([[5, 6],
       [7, 4]])

In [74]:
m2.T

array([[5, 7],
       [6, 4]])

#12. Create a 3x3 array and a 1D array with 3 elements. Add the 1D array to the 2D array. Explain how broadcasting works in this operation.

In [78]:
arr1 = np.array([[4,7,9],
                 [34,32,21],
                 [9,8,7]])
arr2 = np.array([12,23,43])

In [79]:
arr1

array([[ 4,  7,  9],
       [34, 32, 21],
       [ 9,  8,  7]])

In [80]:
arr2

array([12, 23, 43])

In [81]:
arr1 + arr2

array([[16, 30, 52],
       [46, 55, 64],
       [21, 31, 50]])

#13. Create a 4x4 array of random integers. Find the maximum, minimum, and mean of the entire array. 

In [84]:
arr1 = np.random.randint(1,40,16).reshape(4,4)
arr1

array([[ 9, 27, 30, 13],
       [16, 19,  4, 28],
       [36, 16, 23, 18],
       [33, 39, 15, 33]], dtype=int32)

In [85]:
arr1.min()

np.int32(4)

In [86]:
arr1.max()

np.int32(39)

In [87]:
arr1.mean()

np.float64(22.4375)

#14. Find the row-wise and column-wise sums.

In [88]:
arr1

array([[ 9, 27, 30, 13],
       [16, 19,  4, 28],
       [36, 16, 23, 18],
       [33, 39, 15, 33]], dtype=int32)

In [89]:
arr1.sum(axis=0) ## Columnwise sum

array([ 94, 101,  72,  92])

In [91]:
arr1.sum(axis=1) #Rowwise sum

array([ 79,  67,  93, 120])

#15. Generate an array of 10 random integers between 1 and 50. 

In [92]:
random_num = np.random.randint(1,50,10)
random_num

array([ 9, 34, 16, 39, 10,  7, 32, 40, 37, 45], dtype=int32)

#16. Generate a 5x5 matrix of random floats between 0 and 1.

In [95]:
arr1 = np.random.rand(25).reshape(5,5)
arr1

array([[0.06579452, 0.31890212, 0.34948971, 0.95310195, 0.49332605],
       [0.72432811, 0.32958322, 0.68792419, 0.1031397 , 0.07942917],
       [0.55263323, 0.36012086, 0.50116587, 0.64383774, 0.11520322],
       [0.28885326, 0.02635663, 0.38507088, 0.39101   , 0.03051856],
       [0.30334643, 0.71248154, 0.13384449, 0.14382732, 0.61942435]])