In [6]:
a = 30

In [7]:
b = 10

In [8]:
c = a - b

In [9]:
c

20

In [10]:
print(c)

20


In [11]:
a = 3

In [12]:
b = 4

In [13]:
c = a ** b

In [14]:
c

81

In [15]:
c = a*a*a*a

In [16]:
c

81

In [17]:
res = 1
for i in range(b):
    res = res * a
res

81

In [7]:
import numpy as np

In [8]:
arr1 = np.array([2,3,4,5,6])
arr1

array([2, 3, 4, 5, 6])

In [9]:
arr2 = np.array([7,5,4,3,2])
arr2

array([7, 5, 4, 3, 2])

In [8]:
# In a array if we perform the (+) operator they will in execute but in the list it will give the concatination 

In [9]:
# Array is a homogeneous data type && List is a heterogeneous data type 

In [10]:
# Array support vectorization && List Does not support vectorization

In [10]:
arr3 = arr1 + arr2
arr3

array([9, 8, 8, 8, 8])

In [11]:
arr1 = np.array([1, 'FBS', 56.09])
arr1

array(['1', 'FBS', '56.09'], dtype='<U32')

In [15]:
## dtype = <U32 -> Is a unified text data type 
## In a array heterogeneous not work if we write then the output execute in a string format

In [12]:
arr2 = np.array([12,56,90.3])
arr2

array([12. , 56. , 90.3])

In [16]:
## In this output the 12. (.) is a like 0.

In [13]:
arr1.dtype

dtype('<U32')

In [14]:
arr2.dtype

dtype('float64')

In [19]:
# In a after float is a bit(64) 

In [15]:
arr3 = np.array([1,2,3])
arr3.dtype # data type of a element in array

dtype('int64')

In [23]:
arr1.size ## Size of a array

3

In [17]:
arr1.shape ## This will give the shape to the element

(3,)

In [25]:
arr1.ndim ## Number of dimentions

1

In [26]:
arr = np.array([24,56,32])
result = arr > 25

In [28]:
result ## It will give also the output of a element.

array([False,  True,  True])

In [30]:
## List Time 

In [43]:
%%time
list1 = [x for x in range (1, 100001)]
list2 = [x for x in range (100001, 200001)]
list3 = []
for i in range(len (list1)):
    list3.append(list1[i]+list2[i])

CPU times: total: 78.1 ms
Wall time: 49 ms


In [39]:
## Array time

In [42]:
%%time
arr1 = np.array([ x for x in range (1,100001)])
arr2 = np.array([ x for x in range (100001, 200001)])
arr3 = arr1 + arr2

CPU times: total: 46.9 ms
Wall time: 35.3 ms


In [44]:
## List Size 

In [53]:
import sys
list = [34,45,56,67]
sys.getsizeof(list[0] * len(list))

28

In [54]:
## Array Size

In [57]:
arr = np.array([34,45,56,67])
arr.itemsize * arr.size

32