In [1]:
import numpy as np

In [4]:
arr1 = np.array([[1,2,3],[4,5,6]])

In [5]:
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
arr1.ndim ## This will give number of dimention

2

In [9]:
arr1.shape ## This will give shape of element of array.

(2, 3)

In [10]:
arr2 = np.array([[1,2,3,4],
                 [5,6,7,8],
                 [2,9,11,15]])

In [12]:
arr2 ### This one is a 2Dimention 

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 2,  9, 11, 15]])

In [15]:
arr3 = np.array([[[1,2],
                  [3,4]],
                 [[5,6],
                  [7,8]]])
## This one is a 3Dimention 

In [16]:
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [18]:
arr3.shape ## This one give shape of element in array

(2, 2, 2)

In [19]:
arr3.ndim

3

Operation Of Array

In [20]:
arr1 = np.arange(1,21)

In [21]:
arr1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [22]:
arr2 = np.arange(1,25,2)

In [23]:
arr2

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23])

In [24]:
arr1 = np.random.randint(1,100,15)
arr1

array([32, 63, 46, 32, 13, 30, 76, 77, 64, 56, 41,  1, 95, 74, 55],
      dtype=int32)

In [26]:
arr1[2]

np.int32(46)

In [28]:
arr1.min()

np.int32(1)

In [29]:
arr1.max()

np.int32(95)

In [30]:
arr1.sum()

np.int64(755)

In [31]:
arr1.mean()

np.float64(50.333333333333336)

In [32]:
arr1.size

15

In [33]:
arr1

array([32, 63, 46, 32, 13, 30, 76, 77, 64, 56, 41,  1, 95, 74, 55],
      dtype=int32)

In [35]:
arr1 = arr1.reshape(5,3)
arr1

array([[32, 63, 46],
       [32, 13, 30],
       [76, 77, 64],
       [56, 41,  1],
       [95, 74, 55]], dtype=int32)

In [36]:
arr1.shape

(5, 3)

In [18]:
arr1[0]

array([48, 17, 84, 93, 46], dtype=int32)

In [17]:
arr1[0,2] ## This one is a indexing method

np.int32(84)

In [20]:
arr1[2:3] ## This one is slicing method

array([[91, 56, 65, 55, 97]], dtype=int32)

In [2]:
arr1 = np.random.randint(1,100,25)
arr1

array([48, 17, 84, 93, 46, 81, 56, 20, 51, 66, 91, 56, 65, 55, 97, 93, 43,
       55, 92, 97, 40, 25, 92, 39, 49], dtype=int32)

In [5]:
arr1 = arr1.reshape(5,5)
arr1

array([[48, 17, 84, 93, 46],
       [81, 56, 20, 51, 66],
       [91, 56, 65, 55, 97],
       [93, 43, 55, 92, 97],
       [40, 25, 92, 39, 49]], dtype=int32)

In [22]:
arr1[3:4] ## This one is also a slicing

array([[93, 43, 55, 92, 97]], dtype=int32)

In [24]:
arr1[3,4] ## This one is a indexing method.

np.int32(97)

In [16]:
arr1[2:3,3:4] ##Using sling[2:3] and indexing[3,3]

array([[55]], dtype=int32)

In [12]:
arr1[2:4,1:3]

array([[56, 65],
       [43, 55]], dtype=int32)

In [3]:
arr1 = np.linspace(1,10,25)
arr1 ## This one is generate a sequence of evenly spaced consecutive values between two values(start & end point)

array([ 1.   ,  1.375,  1.75 ,  2.125,  2.5  ,  2.875,  3.25 ,  3.625,
        4.   ,  4.375,  4.75 ,  5.125,  5.5  ,  5.875,  6.25 ,  6.625,
        7.   ,  7.375,  7.75 ,  8.125,  8.5  ,  8.875,  9.25 ,  9.625,
       10.   ])

In [6]:
arr2 = np.random.rand(10)
arr2 ## [rand] it will generate any random number between 0 to 1 

array([0.41046068, 0.84911605, 0.96450998, 0.27069267, 0.99004969,
       0.21405402, 0.14558555, 0.04360252, 0.11566969, 0.22302077])

In [8]:
arr3 = np.ones(6)
arr3 ## one method will create a array all is [1 -> 6] and the number is by default is float.

array([1., 1., 1., 1., 1., 1.])

In [12]:
arr4 = np.zeros(10,dtype= 'int') # same as above but we can change the datatype also in both method.
arr4

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
arr5 = np.eye(3,3)
arr5

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [27]:
arr1 = np.random.randint(1,100,30).reshape(5,6)
arr1

array([[40,  6,  3, 64, 33, 45],
       [71, 86,  1, 37, 55, 43],
       [75, 30, 43, 18, 29, 67],
       [90, 33, 70,  7, 30, 94],
       [69,  1, 99, 89, 19,  1]], dtype=int32)

In [28]:
arr1.min(axis=1) # It will return the min value in row index

array([ 3,  1, 18,  7,  1], dtype=int32)

In [29]:
arr1.min(axis=0) # It will return the min value in column

array([40,  1,  1,  7, 19,  1], dtype=int32)

In [30]:
arr1.max(axis=0) # return max in column

array([90, 86, 99, 89, 55, 94], dtype=int32)

In [31]:
arr1.max(axis=1) # Return max in row of index

array([64, 86, 75, 94, 99], dtype=int32)

In [32]:
arr1.min() # It will return only one min value of all index

np.int32(1)

In [34]:
arr1.argmin() # It will return the min value indexing/ position number

np.int64(8)

In [36]:
arr1.argmax() # Return the max value index/position number

np.int64(26)

### Operation on array

In [44]:
arr1 = np.array([45,67,12,40])
arr2 = np.array([10,20,30,40])
arr3 = arr1 + arr2
arr3 ## It will return the [+] operation of a both array

array([55, 87, 42, 80])

In [ ]:
arr1 = np.array([45,67,12,40])
arr2 = np.array([10,20,30,40,50])
arr3 = arr1 + arr2
arr3 # Not executed give the error if we perform operation on element should be same in both array.

## Broadcasting

In [46]:
arr1 = np.array([45,34,54,65])
arr2 = np.array([[23,34,67,87],
                [50,30,20,40]])
arr3 = arr1 + arr2
arr3 # it will execute the opeartion in both array [+] operator == [arr1 + arr2[i]] , [arr1 + arr2[ii]]

array([[ 68,  68, 121, 152],
       [ 95,  64,  74, 105]])

In [47]:
arr1 = np.arange(1,5).reshape(2,2)
arr2 = np.arange(11,15).reshape(2,2)

In [48]:
arr1

array([[1, 2],
       [3, 4]])

In [49]:
arr2

array([[11, 12],
       [13, 14]])

In [52]:
arr2 - arr1

array([[10, 10],
       [10, 10]])

## Conditional selection

In [53]:
arr1 = np.random.randint(1,100,15)
arr1

array([39, 35, 16, 32, 35, 19, 57, 96, 93, 77, 14, 83, 64, 46, 34],
      dtype=int32)

In [60]:
arr1 < 50 ## It will return the array in a True & False

array([[False,  True,  True,  True,  True],
       [False, False, False,  True,  True],
       [ True, False,  True, False, False],
       [ True, False, False, False,  True],
       [ True,  True, False,  True,  True],
       [False,  True, False,  True, False]])

In [55]:
arr1[arr1 < 50] ## it will return the array that less than 50.

array([39, 35, 16, 32, 35, 19, 14, 46, 34], dtype=int32)

In [56]:
arr1 = np.random.randint(1,100,30).reshape(6,5)
arr1

array([[68, 18, 27,  5, 16],
       [78, 50, 65, 21, 42],
       [12, 92, 13, 81, 86],
       [21, 80, 71, 78, 41],
       [30, 17, 68, 34,  6],
       [90, 37, 72, 35, 58]], dtype=int32)

In [58]:
arr1[arr1 %2 ==0] ## It will return the even values in array.

array([68, 18, 16, 78, 50, 42, 12, 92, 86, 80, 78, 30, 68, 34,  6, 90, 72,
       58], dtype=int32)

In [63]:
# Multiple of 3
arr1 [arr1 %3 ==0] ## It will return the number of multiplication of 3 number.

array([18, 27, 78, 21, 42, 12, 81, 21, 78, 30,  6, 90, 72], dtype=int32)

In [64]:
arr1

array([[68, 18, 27,  5, 16],
       [78, 50, 65, 21, 42],
       [12, 92, 13, 81, 86],
       [21, 80, 71, 78, 41],
       [30, 17, 68, 34,  6],
       [90, 37, 72, 35, 58]], dtype=int32)

In [66]:
arr1 [(arr1 > 50 ) & (arr1 < 90)]
## In conditional selection we don't use [and] instead we use [&], and the 1 conditon is present then we don't have to put in paranthesis(),
# but if we have 2 condition then write in paranthesis().

array([68, 78, 65, 81, 86, 80, 71, 78, 68, 72, 58], dtype=int32)